/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data_pembayaran_spp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class input extends javax.swing.JFrame {

    /**
     * Creates new form input
     */
    public input() {
        initComponents();
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mrgn3 = new custom.mrgn();
        mrgn1 = new custom.mrgn();
        jLabel1 = new javax.swing.JLabel();
        mrgn2 = new custom.mrgn();
        jLabel2 = new javax.swing.JLabel();
        v_siswa = new javax.swing.JTextField();
        v_kelas = new javax.swing.JTextField();
        v_simpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        v_nisn = new javax.swing.JTextField();
        mrgn4 = new custom.mrgn();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        mrgn3.setBackground(new java.awt.Color(0, 51, 102));
        mrgn3.setRoundBottomLeft(30);
        mrgn3.setRoundBottomRight(30);
        mrgn3.setRoundTopLeft(30);
        mrgn3.setRoundTopRight(30);

        mrgn1.setBackground(new java.awt.Color(0, 51, 153));
        mrgn1.setRoundBottomLeft(30);
        mrgn1.setRoundBottomRight(30);
        mrgn1.setRoundTopLeft(30);
        mrgn1.setRoundTopRight(30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAMA SISWA");

        javax.swing.GroupLayout mrgn1Layout = new javax.swing.GroupLayout(mrgn1);
        mrgn1.setLayout(mrgn1Layout);
        mrgn1Layout.setHorizontalGroup(
            mrgn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mrgn1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );
        mrgn1Layout.setVerticalGroup(
            mrgn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mrgn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mrgn2.setBackground(new java.awt.Color(0, 51, 153));
        mrgn2.setRoundBottomLeft(30);
        mrgn2.setRoundBottomRight(30);
        mrgn2.setRoundTopLeft(30);
        mrgn2.setRoundTopRight(30);

        jLabel2.setBackground(new java.awt.Color(0, 51, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KELAS_JURUSAN");

        javax.swing.GroupLayout mrgn2Layout = new javax.swing.GroupLayout(mrgn2);
        mrgn2.setLayout(mrgn2Layout);
        mrgn2Layout.setHorizontalGroup(
            mrgn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mrgn2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );
        mrgn2Layout.setVerticalGroup(
            mrgn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mrgn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        v_siswa.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        v_siswa.setText("Masukan nama siswa");
        v_siswa.setMargin(new java.awt.Insets(10, 10, 10, 10));
        v_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_siswaActionPerformed(evt);
            }
        });

        v_kelas.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        v_kelas.setText("Masukan kelas");
        v_kelas.setMargin(new java.awt.Insets(10, 10, 10, 10));

        v_simpan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        v_simpan.setText("SAVE");
        v_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_simpanMouseClicked(evt);
            }
        });
        v_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_simpanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data_pembayaran_spp/was.png"))); // NOI18N
        jLabel3.setText("TAMBAH SISWA");

        v_nisn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        v_nisn.setText("Masukan Nisn siswa");
        v_nisn.setMargin(new java.awt.Insets(10, 10, 10, 10));

        mrgn4.setBackground(new java.awt.Color(0, 51, 153));
        mrgn4.setRoundBottomLeft(30);
        mrgn4.setRoundBottomRight(30);
        mrgn4.setRoundTopLeft(30);
        mrgn4.setRoundTopRight(30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NISN");

        javax.swing.GroupLayout mrgn4Layout = new javax.swing.GroupLayout(mrgn4);
        mrgn4.setLayout(mrgn4Layout);
        mrgn4Layout.setHorizontalGroup(
            mrgn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mrgn4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        mrgn4Layout.setVerticalGroup(
            mrgn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mrgn4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mrgn3Layout = new javax.swing.GroupLayout(mrgn3);
        mrgn3.setLayout(mrgn3Layout);
        mrgn3Layout.setHorizontalGroup(
            mrgn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mrgn3Layout.createSequentialGroup()
                .addGroup(mrgn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mrgn3Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel3))
                    .addGroup(mrgn3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(mrgn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(v_nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mrgn3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mrgn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mrgn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mrgn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mrgn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v_simpan)
                            .addGroup(mrgn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(v_siswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(v_kelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        mrgn3Layout.setVerticalGroup(
            mrgn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mrgn3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(mrgn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mrgn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(v_nisn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(mrgn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mrgn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(v_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(mrgn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mrgn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(v_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(v_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(mrgn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(mrgn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void v_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_siswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_siswaActionPerformed

    private void v_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_simpanMouseClicked
         this.setVisible(false);
    }//GEN-LAST:event_v_simpanMouseClicked

    private void v_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_simpanActionPerformed
       String NISN = v_nisn.getText();
        String NAMA_SISWA =v_siswa.getText();
        String KELAS_JURUSAN = v_kelas.getText();

        try {
            // Membuat koneksi ke database menggunakan metode getConnection dari kelas koneksi
            Connection con = koneksi.getConnection();

            // Menyusun query INSERT
            String query = "INSERT INTO spp (NISN, NAMA_SISWA, KELAS_JURUSAN) VALUES (?, ?, ?)";

            // Membuat PreparedStatement untuk mencegah SQL injection
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, NISN);
            ps.setString(2, NAMA_SISWA);
            ps.setString(3, KELAS_JURUSAN);

            // Menjalankan query INSERT
            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menambahkan data");
            }

            // Menutup PreparedStatement dan koneksi
            //ps.close();
            //con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi database gagal: " + e.getMessage());
        }
         data_siswa dataSiswaFrame = new data_siswa();
         dataSiswaFrame.setVisible(true);
         this.dispose();
    
    }//GEN-LAST:event_v_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private custom.mrgn mrgn1;
    private custom.mrgn mrgn2;
    private custom.mrgn mrgn3;
    private custom.mrgn mrgn4;
    private javax.swing.JTextField v_kelas;
    private javax.swing.JTextField v_nisn;
    private javax.swing.JButton v_simpan;
    private javax.swing.JTextField v_siswa;
    // End of variables declaration//GEN-END:variables
}
